[package]
name = "create2-vanity-miner"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
ethers = "1.0.0"
serde = { version = "1.0.217", features = ["derive"] }
hex = "0.4.3"
rayon = "1.10.0"
serde_json = "1.0.135"
rand = "0.9.0-beta.3"
thiserror = "1.0.69"
